-- MySQL Script generated by MySQL Workbench
-- Wed Oct  2 13:15:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Farmacia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Farmacia` ;

-- -----------------------------------------------------
-- Schema Farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Farmacia` DEFAULT CHARACTER SET utf8 ;
USE `Farmacia` ;

-- -----------------------------------------------------
-- Table `Farmacia`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Password` BLOB NOT NULL,
  `Jerarquia` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(120) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Edad` VARCHAR(5) NOT NULL,
  `Puntos` INT NOT NULL,
  `Rfc` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Direccion` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Presentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Presentacion` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Presentacion` (
  `idPresentacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPresentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Producto` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Cod_Barras` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(120) NOT NULL,
  `Presentacion` INT NOT NULL,
  `Proveedor` INT NOT NULL,
  `Precio_Compra` FLOAT NOT NULL,
  `Precio_Venta` FLOAT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Receta` TINYINT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `Proveedor_idx` (`Proveedor` ASC) VISIBLE,
  INDEX `idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `idPresentacion_idx` (`Presentacion` ASC) VISIBLE,
  CONSTRAINT `Proveedor`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `Farmacia`.`Proveedor` (`idProveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `Farmacia`.`Categorias` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPresentacion`
    FOREIGN KEY (`Presentacion`)
    REFERENCES `Farmacia`.`Presentacion` (`idPresentacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Venta` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Total` FLOAT NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `Farmacia`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Detalle_Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Detalle_Venta` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Detalle_Venta` (
  `idVenta` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idCliente` INT NULL,
  `Precio_Venta` DOUBLE NOT NULL,
  `Precio_Compra` DOUBLE NOT NULL,
  INDEX `idVenta_idx` (`idVenta` ASC) VISIBLE,
  INDEX `idProducto_idx` (`idProducto` ASC) VISIBLE,
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idVenta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `Farmacia`.`Venta` (`idVenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Farmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Farmacia`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Compra` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Compra` (
  `idProveedor` INT NOT NULL,
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `Total_Compra` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  INDEX `idProveedor_idx` (`idProveedor` ASC) VISIBLE,
  PRIMARY KEY (`idCompra`),
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `Farmacia`.`Proveedor` (`idProveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Promocion` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Promocion` (
  `idPromocion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(120) NOT NULL,
  `Activa` TINYINT NOT NULL,
  PRIMARY KEY (`idPromocion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Detalle_Promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Detalle_Promocion` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Detalle_Promocion` (
  `idPromocion` INT NOT NULL,
  `idProducto` INT NOT NULL,
  INDEX `idPromocion_idx` (`idPromocion` ASC) VISIBLE,
  INDEX `idProducto_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `idPromocion`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `Farmacia`.`Promocion` (`idPromocion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Farmacia`.`Producto` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Detalle_Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Detalle_Compra` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Detalle_Compra` (
  `idProducto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `idCompra` INT NOT NULL,
  `Precio_Compra` FLOAT NOT NULL,
  INDEX `idCompra_idx` (`idCompra` ASC) VISIBLE,
  CONSTRAINT `idCompra`
    FOREIGN KEY (`idCompra`)
    REFERENCES `Farmacia`.`Compra` (`idCompra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
